# ===================================
# Application Info
# ===================================
spring.application.name=gym-saas-backend

# ===================================
# Database Configuration
# ===================================
#spring.datasource.url=jdbc:mysql://localhost:3306/gym_db?allowPublicKeyRetrieval=true&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=1champ@tushaR
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://database-1gymsaas.clgegam20a98.ap-south-1.rds.amazonaws.com:3308/gym_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=admin
spring.datasource.password=1champtushaR
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ===================================
# Flyway Configuration
# ===================================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false
spring.flyway.validate-on-migrate=true
spring.flyway.clean-on-validation-error=true

# ===================================
# JPA / Hibernate
# ===================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===================================
# Hikari Connection Pool
# ===================================
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

# ===================================
# Logging for Debugging
# ===================================
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.jdbc=DEBUG

jwt.secret=your-very-strong-secret-key-change-this
jwt.expiration=3600000 # optional: 1 hour in milliseconds

app.send.excel.to=tushar26g@gmail.com

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=26demonking@gmail.com
spring.mail.password=rpgy urnl bbbq dfdv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

twilio.account-sid=ACd3b0568f5ea92f8fb7de83ed02836429
twilio.auth-token=4a3c6a696966b9e0f9dfd3425c9f3e91
twilio.trial-number=+13159544730
